server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blogdb?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234
  jpa:
    database: mysql   # 추가 해준 부분
    database-platform: org.hibernate.dialect.MySQL8Dialect # 추가 해준 부분
    hibernate:
      ddl-auto: none
    properties:
      default_batch_fetch_size: 100
    open-in-view: false

  data:
    redis:
      port: 6379
      host: localhost

logging:
  level:
    '[shop.mtcoding.springblogriver]': INFO
    '[org.hibernate.type]': TRACE

file:
  path: ./images/
